### ISSUE TITLE
No module named 'bpy'

### ISSUE THREAD

**Issue by FurkanGozukara** [avatechai/avatar-graph-comfyui#12]
Hello. I am working on a tutorial for your repo

Trying to make static animated image but getting this error

I did a fresh installation of ComfyUI for releases page

Installed your repo from node manager

It doesn't show any error

![image](https://github.com/avatechai/avatar-graph-comfyui/assets/19240467/be3f2716-552c-48d5-8717-cbb0e714586e)

```
C:\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
** ComfyUI start up time: 2023-10-31 01:03:45.321965

Prestartup times for custom nodes:
   0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 24564 MB, total RAM 65304 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 Ti : cudaMallocAsync
VAE dtype: torch.bfloat16
Using pytorch cross attention
### Loading: ComfyUI-Manager (V0.36)
### ComfyUI Revision: 1627 [aac8fc99] | Released on '2023-10-28'

Import times for custom nodes:
   0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\avatar-graph-comfyui
   0.3 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json
got prompt
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\avatar-graph-comfyui\blender\blender_node.py", line 100, in process
    import global_bpy
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\avatar-graph-comfyui\global_bpy.py", line 1, in <module>
    import bpy
ModuleNotFoundError: No module named 'bpy'

Prompt executed in 0.01 seconds

```

**Comment by FurkanGozukara** [comment]
i tried these too no luck

![image](https://github.com/avatechai/avatar-graph-comfyui/assets/19240467/1ac5309a-3305-44c7-a3fb-27f6aba3c39c)

**Comment by FurkanGozukara** [comment]
the problem definitely related to embedded python exe

it is using python 3.11.6

**Comment by FurkanGozukara** [comment]
ok i made it work 

but how to save generated animated image as gif or animated png?

**Comment by BennyKok** [comment]
Sorry for the late reply, currently you can simply do a screen capture or share the avatar -> capture on your own from the avatar viewer. Let me reply the another problem from discord

**Comment by thewhi1991** [comment]
ok...how do you make it work? im try but nothing work.

**Comment by FurkanGozukara** [comment]
> ok...how do you make it work? im try but nothing work.

i manually installed comfyui with python 3.10.11

here manual installer : https://www.patreon.com/posts/92013455

**Comment by Radionic** [comment]
@thewhi1991 Please refer to the latest installation guide
