### ISSUE TITLE
issue: blender nodes not registering correctly.

### ISSUE THREAD

**Issue by ltdrdata** [avatechai/avatar-graph-comfyui#3]
Whenever the browser loads, I always encounter this error.

```
[ERROR] An error occurred while retrieving information for the 'UV_Unwrap' node.
Traceback (most recent call last):
  File "/home/me/git/ComfyUI/server.py", line 417, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "/home/me/git/ComfyUI/server.py", line 395, in node_info
    info['input'] = obj_class.INPUT_TYPES()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/me/git/ComfyUI/custom_nodes/avatar-graph-comfyui/blender/blender_node.py", line 50, in INPUT_TYPES
    return node_input_types[cls.__name__]
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'UV_Unwrap'
```

**Comment by BennyKok** [comment]
Thanks! How do you spot this so fast? we just published this last night haha, @Radionic will be taking a look into this.

**Comment by BennyKok** [comment]
Are you loading one of the templates and getting this error? Seems like the template is outdated, we removed that node previously.

**Comment by ltdrdata** [comment]
I came across it while browsing the recent list of custom nodes on GitHub.

I simply installed this custom node without any settings and opened the browser of an empty workflow.
When I tried it on a different machine, I didn't encounter this error. (I will recheck this in the same environment later.)

However, it seems that the current structure of loading the module is causing conflicts with other custom nodes, leading to random issues. It's confirmed that there is a conflict with the comfyui_controlnet_aux custom node, at least for now.

It's possible that the issue I initially reported may have been caused by a conflict between custom nodes, resulting in the import of some modules getting tangled. 

```

Traceback (most recent call last):
  File "/home/me/github/ComfyUI/nodes.py", line 1734, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/me/github/ComfyUI/custom_nodes/avatar-graph-comfyui/__init__.py", line 94, in <module>
    module = importlib.import_module(file)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/me/github/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/controlnet_aux/sam/__init__.py", line 17, in <module>
    from ..util import HWC3, common_input_validate, resize_image_with_pad
ImportError: attempted relative import beyond top-level package
Cannot import /home/me/github/ComfyUI/custom_nodes/avatar-graph-comfyui module for custom nodes: attempted relative import beyond top-level package
```

**Comment by Radionic** [comment]
Thanks for the info! The "KeyError: 'UV_Unwrap'" issue shall be fixed.

As for the conflict with comfyui_controlnet_aux node, I tried to install it alongside our custom node, but I didn't encounter any error when I restart ComfyUI. Would you mind providing a complete list of installed custom nodes?

**Comment by ltdrdata** [comment]
> Thanks for the info! The "KeyError: 'UV_Unwrap'" issue shall be fixed.
> 
> As for the conflict with comfyui_controlnet_aux node, I tried to install it alongside our custom node, but I didn't encounter any error when I restart ComfyUI. Would you mind providing a complete list of installed custom nodes?

First of all, here is the list.

```
Import times for custom nodes:
   0.0 seconds: /home/me/github/ComfyUI/custom_nodes/sampler_tonemap.py
   0.0 seconds: /home/me/github/ComfyUI/custom_nodes/sdxl_prompt_styler
   0.0 seconds: /home/me/github/ComfyUI/custom_nodes/sd-dynamic-thresholding
   0.0 seconds: /home/me/github/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus
   0.0 seconds: /home/me/github/ComfyUI/custom_nodes/advanced_model_merging.py
   0.0 seconds: /home/me/github/ComfyUI/custom_nodes/PPF_Noise_ComfyUI
   0.0 seconds: /home/me/github/ComfyUI/custom_nodes/ComfyUI-Inspire-Pack
   0.0 seconds: /home/me/github/ComfyUI/custom_nodes/ComfyUI-Custom-Scripts
   0.0 seconds: /home/me/github/ComfyUI/custom_nodes/efficiency-nodes-comfyui
   0.0 seconds: /home/me/github/ComfyUI/custom_nodes/ComfyUI_experiments
   0.0 seconds: /home/me/github/ComfyUI/custom_nodes/AIGODLIKE-COMFYUI-TRANSLATION
   0.0 seconds (IMPORT FAILED): /home/me/github/ComfyUI/custom_nodes/avatar-graph-comfyui
   0.0 seconds: /home/me/github/ComfyUI/custom_nodes/comfyui_controlnet_aux
   0.0 seconds: /home/me/github/ComfyUI/custom_nodes/ComfyUI-Manager
   0.1 seconds: /home/me/github/ComfyUI/custom_nodes/numba_test.py
   0.2 seconds: /home/me/github/ComfyUI/custom_nodes/clipseg.py
   1.3 seconds: /home/me/github/ComfyUI/custom_nodes/ComfyUI-Impact-Pack
```

However, based on my observations, it appears that there is a collision between the path of `controlnet_aux/sam` and the path of `avatar/sam`. The order in which avatar and cnet aux are imported could also be a potential issue.

**Comment by Radionic** [comment]
Just fixed, you may try again to see if the errors still exist.

**Comment by ltdrdata** [comment]
Now there is no problem. Thank you. :)

**Comment by BennyKok** [comment]
Thanks for adding to comfyui manger!
