### ISSUE TITLE
Hard crash when output already exists

### ISSUE THREAD

**Issue by chrish-slingshot** [avatechai/avatar-graph-comfyui#9]
When running, if the .ava file already exists in the output directory then the avatar main output node crashes and you need to restart ComfyUI before the workflow will work again.

**Comment by Radionic** [comment]
Hi, could you provide the workflow you are using and the error logs for us to debug? Thanks.

**Comment by SmashinFries** [comment]
I'm also having this issue.

workflow: [SimpleEye+MouthMovement.json](https://github.com/avatechai/avatar-graph-comfyui/files/13031967/SimpleEye%2BMouthMovement.json)

Error:
```
Exception in thread Thread-5 (prompt_worker):
Traceback (most recent call last):
  File "T:\AI\UI\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "T:\AI\UI\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "T:\AI\UI\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "T:\AI\UI\ComfyUI\custom_nodes\avatar-graph-comfyui\blender\blender_node.py", line 106, in process
    results = self.blender_process(bpy, **props)
  File "T:\AI\UI\ComfyUI\custom_nodes\avatar-graph-comfyui\blender\avatar_main_output.py", line 68, in blender_process
    filepath = export_gltf(
  File "T:\AI\UI\ComfyUI\custom_nodes\avatar-graph-comfyui\blender\mesh_utils.py", line 242, in export_gltf
    os.rename(filepath, new_filepath)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'T:\\AI\\UI\\ComfyUI\\output/GLB.ava.glb' -> 'T:\\AI\\UI\\ComfyUI\\output/GLB.ava'
```

**Comment by Radionic** [comment]
Thanks for helping to resolve the issue.
